### ISSUE TITLE
Any1 have idea ?

### ISSUE THREAD

**Issue by b4xster** [ryan-rowland/albion-guildbot#17]
`pi@raspberrypi:~/Desktop/killbot $ npm start

> albion-guildbot@1.0.0-dev start /home/pi/Desktop/killbot
> npm run build && node lib/index.js

> albion-guildbot@1.0.0-dev build /home/pi/Desktop/killbot
> tsc && copyfiles -u 1 src/*.js lib

info: Connected
info: Logged in as: XXX
info: Checking battles...
info: Checking killboard...
(node:23966) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'indexOf' of undefined
    at events.sort.filter.filter.forEach.event (/home/pi/Desktop/killbot/lib/index.js:228:33)
    at Array.forEach (<anonymous>)
    at Albion.getEvents.then.events (/home/pi/Desktop/killbot/lib/index.js:224:8)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:23966) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:23966) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`
`pi@raspberrypi:~/Desktop/killbot $ node -v
v10.9.0
pi@raspberrypi:~/Desktop/killbot $ npm -v
6.2.0
`

**Comment by jSilla** [comment]
My guess is a wrong 'guilds' entry in config.js. Did you use environment variables or changed the config.js file?
A correct entry in config.js would be eg:
...
    guilds: ['guildname'],
...
Setting the environment variable is described in the Readme, thats why my guess is you changed the config.js. Maybe this helps. Good luck ;)

**Comment by Eragos** [comment]
Please provide your config.js to get a deeper look into that.
